name: Deploy Notification Bots

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest

    strategy:
      matrix:
        bot:
          - name: 35x
            image: m0ln1z/selenium-bot-35x
            bot_token: BOT_TOKEN
            chat_id: CHAT_ID
          - name: 234x
            image: m0ln1z/selenium-bot-234x
            bot_token: BOT_TOKEN_234X
            chat_id: CHAT_ID_234X

    steps:
      # 1. Клонирование репозитория
      - name: Checkout repository
        uses: actions/checkout@v3

      # 2. Формирование тега Docker-образа на основе короткого SHA коммита
      - name: Set Docker image tag
        id: set_tag
        run: |
          TAG=$(git rev-parse --short HEAD)
          echo "DOCKER_TAG=${TAG}" >> $GITHUB_ENV
          echo "Docker tag set to ${TAG}"

      # 3. Логин в Docker Hub
      - name: Login to Docker Hub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}

      # 4. Сборка и пуш Docker-образа
      - name: Build and push Docker image
        uses: docker/build-push-action@v4
        with:
          context: .
          push: true
          tags: "${{ matrix.bot.image }}:${{ env.DOCKER_TAG }}"

      # 5. Деплой на сервер
      - name: Deploy to server
        uses: appleboy/ssh-action@v0.1.5
        with:
          host: ${{ secrets.SSH_HOST }}
          username: ${{ secrets.SSH_USER }}
          password: ${{ secrets.SSH_PASSWORD }}
          script: |
            echo "Connected to server."

            # Проверка наличия Docker
            if ! command -v docker &> /dev/null
            then
                echo "Docker не установлен. Устанавливаем Docker..."
                sudo apt-get update
                sudo apt-get install -y docker.io
                sudo systemctl start docker
                sudo systemctl enable docker
            else
                echo "Docker уже установлен."
            fi

            # Логин в Docker Hub
            echo "${{ secrets.DOCKER_PASSWORD }}" | docker login -u "${{ secrets.DOCKER_USERNAME }}" --password-stdin

            # Пулл обновлённого образа
            docker pull ${{ matrix.bot.image }}:${{ env.DOCKER_TAG }}

            # Остановка и удаление старого контейнера
            docker stop selenium-bot-${{ matrix.bot.name }} || docker kill selenium-bot-${{ matrix.bot.name }} || true
            docker rm -f selenium-bot-${{ matrix.bot.name }} || true

            # Запуск нового контейнера с передачей переменных окружения
            docker run -d \
              --name selenium-bot-${{ matrix.bot.name }} \
              --restart=unless-stopped \
              --memory=2g \
              --memory-swap=2g \
              --cpus=2 \
              --shm-size=256m \
              -e BOT_TOKEN='${{ secrets[matrix.bot.bot_token] }}' \
              -e CHAT_ID='${{ secrets[matrix.bot.chat_id] }}' \
              ${{ matrix.bot.image }}:${{ env.DOCKER_TAG }}