name: Deploy Notification Bot
on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Set Docker image tag
        id: set_tag
        run: |
          TAG=$(git rev-parse --short HEAD)
          echo "DOCKER_TAG=${TAG}" >> $GITHUB_ENV
          echo "Docker tag set to ${TAG}"

      - name: Login to Docker Hub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}

      # Optionally remove the Clear Docker cache step
      # - name: Clear Docker cache
      #   run: |
      #     docker system prune -a -f

      - name: Build and push Docker image
        run: |
          echo "Listing directory contents:"
          ls -la
          echo "Displaying Dockerfile contents:"
          cat Dockerfile
          docker build -t "m0ln1z/selenium-bot:${{ env.DOCKER_TAG }}" .
          
          # Retry logic for docker push
          for i in {1..3}; do
            docker push "m0ln1z/selenium-bot:${{ env.DOCKER_TAG }}" && break
            echo "Push failed, retrying in 10 seconds..."
            sleep 10
          done

      - name: Deploy to server
        env:
          SSH_HOST: ${{ secrets.SSH_HOST }}
          SSH_USER: ${{ secrets.SSH_USER }}
          SSH_PASSWORD: ${{ secrets.SSH_PASSWORD }}
          DOCKER_TAG: ${{ env.DOCKER_TAG }}
          BOT_TOKEN: ${{ secrets.BOT_TOKEN }}
          BOT_TOKEN_234X: ${{ secrets.BOT_TOKEN_234X }}
          CHAT_ID: ${{ secrets.CHAT_ID }}
          CHAT_ID_234X: ${{ secrets.CHAT_ID_234X }}
        run: |
          sshpass -p "${SSH_PASSWORD}" ssh -o StrictHostKeyChecking=no ${SSH_USER}@${SSH_HOST} "
          docker pull m0ln1z/selenium-bot:${DOCKER_TAG} &&
          docker stop selenium-bot || docker kill selenium-bot || true &&
          docker rm -f selenium-bot || true &&
          docker run -d \
            --name selenium-bot \
            --restart=always \
            --memory=2g \
            --memory-swap=2g \
            --cpus=2 \
            --shm-size=4g \
            -e BOT_TOKEN=${BOT_TOKEN} \
            -e BOT_TOKEN_234X=${BOT_TOKEN_234X} \
            -e CHAT_ID=${CHAT_ID} \
            -e CHAT_ID_234X=${CHAT_ID_234X} \
            m0ln1z/selenium-bot:${DOCKER_TAG}
          "