name: Deploy Bot

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      # 1. Клонирование репозитория
      - name: Checkout repository
        uses: actions/checkout@v3

      # 2. Установка Docker
      - name: Set up Docker
        run: |
          sudo apt-get update
          sudo apt-get install -y docker.io

      # 3. Вход в Docker Hub
      - name: Login to Docker Hub
        env:
          DOCKER_USERNAME: ${{ secrets.DOCKER_USERNAME }}
          DOCKER_PASSWORD: ${{ secrets.DOCKER_PASSWORD }}
        run: echo "${DOCKER_PASSWORD}" | docker login -u "${DOCKER_USERNAME}" --password-stdin

      # 4. Сборка и пуш Docker-образа
      - name: Build and push Docker image
        run: |
          docker build -t "${{ secrets.DOCKER_USERNAME }}/selenium-bot:latest" .
          docker push "${{ secrets.DOCKER_USERNAME }}/selenium-bot:latest"

      # 5. Деплой на сервер
      - name: Deploy to server
        env:
          SSH_HOST: ${{ secrets.SSH_HOST }}
          SSH_USER: ${{ secrets.SSH_USER }}
          SSH_PASSWORD: ${{ secrets.SSH_PASSWORD }}
        run: |
          sudo apt-get install -y sshpass
          sshpass -p "${SSH_PASSWORD}" ssh -o StrictHostKeyChecking=no ${SSH_USER}@${SSH_HOST} "
          docker pull ${{ secrets.DOCKER_USERNAME }}/selenium-bot:latest &&
          docker stop selenium-bot || true &&
          docker rm selenium-bot || true &&
          docker run -d --name selenium-bot ${{ secrets.DOCKER_USERNAME }}/selenium-bot:latest
          "
