name: Deploy Notification Bot
on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Set Docker image tag
        id: set_tag
        run: |
          TAG=$(git rev-parse --short HEAD)
          echo "DOCKER_TAG=${TAG}" >> $GITHUB_ENV
          echo "Docker tag set to ${TAG}"

      - name: Login to Docker Hub
        env:
          DOCKER_USERNAME: ${{ secrets.DOCKER_USERNAME }}
          DOCKER_PASSWORD: ${{ secrets.DOCKER_PASSWORD }}
        run: |
          echo "${DOCKER_PASSWORD}" | docker login -u "${DOCKER_USERNAME}" --password-stdin

      - name: Clear Docker cache
        run: |
          docker system prune -a -f

      - name: Build and push Docker image
        run: |
          echo "Проверяем содержимое директории:"
          ls -la
          echo "Содержимое Dockerfile:"
          cat Dockerfile
          docker build -t "m0ln1z/selenium-bot:${{ env.DOCKER_TAG }}" .
          docker push "m0ln1z/selenium-bot:${{ env.DOCKER_TAG }}"

      - name: Deploy to server
        env:
          SSH_HOST: ${{ secrets.SSH_HOST }}
          SSH_USER: ${{ secrets.SSH_USER }}
          SSH_PASSWORD: ${{ secrets.SSH_PASSWORD }}
          DOCKER_TAG: ${{ env.DOCKER_TAG }}
          BOT_TOKEN: ${{ secrets.BOT_TOKEN }}
          BOT_TOKEN_234X: ${{ secrets.BOT_TOKEN_234X }}
          CHAT_ID: ${{ secrets.CHAT_ID }}
          CHAT_ID_234X: ${{ secrets.CHAT_ID_234X }}
        run: |
          sshpass -p "${SSH_PASSWORD}" ssh -o StrictHostKeyChecking=no ${SSH_USER}@${SSH_HOST} "
          docker pull m0ln1z/selenium-bot:${DOCKER_TAG} &&
          docker stop selenium-bot || docker kill selenium-bot || true &&
          docker rm -f selenium-bot || true &&
          docker run -d \
            --name selenium-bot \
            --restart=always \
            --memory=2g \
            --memory-swap=2g \
            --cpus=2 \
            --shm-size=256m \
            -e BOT_TOKEN=${BOT_TOKEN} \
            -e BOT_TOKEN_234X=${BOT_TOKEN_234X} \
            -e CHAT_ID=${CHAT_ID} \
            -e CHAT_ID_234X=${CHAT_ID_234X} \
            m0ln1z/selenium-bot:${DOCKER_TAG}
          "