name: Deploy Bot

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      # 1. Клонирование репозитория
      - name: Checkout repository
        uses: actions/checkout@v3

      # 2. Вход в Docker Hub
      - name: Login to Docker Hub
        env:
          DOCKER_USERNAME: ${{ secrets.DOCKER_USERNAME }}
          DOCKER_PASSWORD: ${{ secrets.DOCKER_PASSWORD }}
        run: echo "${DOCKER_PASSWORD}" | docker login -u "${DOCKER_USERNAME}" --password-stdin

      # 3. Сборка и пуш Docker-образа
      - name: Build and push Docker image
        run: |
          docker build -t "m0ln1z/selenium-bot:latest" .
          docker push "m0ln1z/selenium-bot:latest"

      # 4. Деплой на сервер
      - name: Deploy to server
        env:
          SSH_HOST: ${{ secrets.SSH_HOST }}
          SSH_USER: ${{ secrets.SSH_USER }}
          SSH_PASSWORD: ${{ secrets.SSH_PASSWORD }}
        run: |
          sudo apt-get update
          sudo apt-get install -y sshpass docker.io
          sudo systemctl start docker
          sudo systemctl enable docker
          sshpass -p "${SSH_PASSWORD}" ssh -o StrictHostKeyChecking=no ${SSH_USER}@${SSH_HOST} "
          echo 'Checking Docker version' &&
          docker --version &&
          echo 'Logging into Docker Hub' &&
          docker login -u '${{ secrets.DOCKER_USERNAME }}' -p '${{ secrets.DOCKER_PASSWORD }}' &&
          echo 'Pulling the Docker image' &&
          docker pull m0ln1z/selenium-bot:latest &&
          echo 'Stopping and removing the old container' &&
          docker stop selenium-bot || true &&
          docker rm selenium-bot || true &&
          echo 'Running new container' &&
          docker run -d \
          --name selenium-bot \
          --memory=1g \
          --memory-swap=1g \
          --cpus=0.7 \
          --shm-size=421m \
          m0ln1z/selenium-bot:latest
          "
